# Generated by Django 5.2.5 on 2025-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('totale_ore', models.FloatField(default=0)),
            ],
        ),
    ]
