# Generated by Django 5.2.5 on 2025-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='anziano_autosufficiente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='anziano_non_autosufficiente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='assistenza_domiciliare_integrata',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='contratti_privati',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='disabile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='distretto_nord',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='distretto_sud',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='emergenza_caldo_asl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='emergenza_caldo_comune',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='hcp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='minori_disabili_gravi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='nord_ovest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='pnrr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='progetto_sod',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='sud_est',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='sud_ovest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='ufficio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='via_tesso',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
