# Generated by Django 5.2.5 on 2025-08-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0002_utente_anziano_autosufficiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='assistenza_domiciliare_integrata',
            field=models.FloatField(default=0),
        ),
    ]
