# Generated by Django 5.2.5 on 2025-08-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0003_alter_utente_assistenza_domiciliare_integrata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='anziano_autosufficiente',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='anziano_non_autosufficiente',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='contratti_privati',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='disabile',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='distretto_nord',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='distretto_sud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='emergenza_caldo_asl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='emergenza_caldo_comune',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='hcp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='minori_disabili_gravi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='nord_ovest',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='pnrr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='progetto_sod',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='sud_est',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='sud_ovest',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='ufficio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utente',
            name='via_tesso',
            field=models.FloatField(default=0),
        ),
    ]
