# Generated by Django 5.2.5 on 2025-08-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0004_alter_utente_anziano_autosufficiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='data_riferimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
