# Generated by Django 5.2.5 on 2025-08-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0005_utente_data_riferimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
