# Generated by Django 5.2.5 on 2025-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0006_alter_utente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='apl',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='utente',
            name='tipologia',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
