# Generated by Django 5.2.5 on 2025-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0007_utente_apl_utente_tipologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
