# Generated by Django 5.2.5 on 2025-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0008_alter_utente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='distretto',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='utente',
            name='oretotmese',
            field=models.FloatField(default=0),
        ),
    ]
