# Generated by Django 5.2.5 on 2025-09-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0009_utente_distretto_utente_oretotmese'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='buonoservizio',
            field=models.FloatField(default=0),
        ),
    ]
