# Generated by Django 5.2.5 on 2025-09-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0010_utente_buonoservizio'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='tariffa',
            field=models.FloatField(default=0),
        ),
    ]
