# Generated by Django 5.2.5 on 2025-09-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0011_utente_tariffa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariffa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=50)),
                ('valore', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
