# Generated by Django 5.2.5 on 2025-09-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0012_tariffa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffa',
            name='apl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
