# Generated by Django 5.2.6 on 2025-09-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0013_tariffa_apl'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='descrizionetipologia',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
