# Generated by Django 5.2.6 on 2025-10-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0014_utente_descrizionetipologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='distretto_nord_est',
            field=models.FloatField(default=0),
        ),
    ]
