# Generated by Django 5.2.6 on 2025-10-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0015_utente_distretto_nord_est'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='lavoratore',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
