# Generated by Django 5.2.6 on 2025-10-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0016_utente_lavoratore'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffa',
            name='descrizionetipologia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
