# Generated by Django 5.2.6 on 2025-10-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0017_tariffa_descrizionetipologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='periodo_documento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
