# Generated by Django 5.2.6 on 2025-10-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0018_utente_periodo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='periodo_documento',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
