# Generated by Django 5.2.6 on 2026-02-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0019_alter_utente_periodo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='residuo_ore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='utente',
            name='totale_foglifirma',
            field=models.FloatField(default=0),
        ),
    ]
