# Generated by Django 5.2.6 on 2026-02-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0020_utente_residuo_ore_utente_totale_foglifirma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='residuo_ore',
        ),
    ]
