# Generated by Django 5.2.6 on 2026-02-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0021_remove_utente_residuo_ore'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='row_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
