# Generated by Django 5.2.6 on 2026-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0022_utente_row_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
